apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-etc
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- $memcachedFullname := include "keystone.cacheHost" . }}
  {{- $memcachedPort := include "keystone.cachePort" . | int }}
  keystone.sh: |-
    echo "
    [DEFAULT]
    debug = False
    transport_url = rabbit://{{ include "keystone.rabbitmq.user" . }}:$RABBITMQ_PASSWORD@{{ include "keystone.rabbitmq.host" . }}:{{ include "keystone.rabbitmq.port" . }}
    use_stderr = True
    [oslo_middleware]
    enable_proxy_headers_parsing = True
    [token]
    revoke_by_id = False
    provider = fernet
    expiration = 86400
    allow_expired_window = 172800
    [fernet_tokens]
    max_active_keys = 3
    [cache]
    backend = dogpile.cache.memcached
    enabled = {{ index .Values "openstack-dep" "memcached" "enabled" }}
    memcache_servers = {{ $memcachedFullname }}:{{  $memcachedPort }}
    [oslo_messaging_notifications]
    transport_url = rabbit://{{ include "keystone.rabbitmq.user" . }}:$RABBITMQ_PASSWORD@{{ include "keystone.rabbitmq.host" . }}:{{ include "keystone.rabbitmq.port" . }}
    driver = messagingv2
    topics = barbican_notifications
    [database]
    connection = mysql+pymysql://{{ include "keystone.databaseUser" . }}:$KEYSTONE_DATABASE_PASSWORD@{{ include "keystone.databaseHost" . }}:{{ include "keystone.databasePort" . }}/{{ include "keystone.databaseName" . }}
    connection_recycle_time = 10
    max_pool_size = 1
    max_retries = -1
    " > /etc/keystone/keystone.conf
  access_rules.json: |-
    {}
  logging.conf: |-
    [formatter_context]
    class = oslo_log.formatters.ContextFormatter
    datefmt = %Y-%m-%d %H:%M:%S
    [formatter_default]
    datefmt = %Y-%m-%d %H:%M:%S
    format = %(message)s
    [formatters]
    keys = context,default
    [handler_null]
    args = ()
    class = logging.NullHandler
    formatter = default
    [handler_stderr]
    args = (sys.stderr,)
    class = StreamHandler
    formatter = context
    [handler_stdout]
    args = (sys.stdout,)
    class = StreamHandler
    formatter = context
    [handlers]
    keys = stdout,stderr,null
    [logger_amqp]
    handlers = stderr
    level = WARNING
    qualname = amqp
    [logger_amqplib]
    handlers = stderr
    level = WARNING
    qualname = amqplib
    [logger_boto]
    handlers = stderr
    level = WARNING
    qualname = boto
    [logger_eventletwsgi]
    handlers = stderr
    level = WARNING
    qualname = eventlet.wsgi.server
    [logger_keystone]
    handlers = stdout
    level = INFO
    qualname = keystone
    [logger_root]
    handlers = null
    level = WARNING
    [logger_sqlalchemy]
    handlers = stderr
    level = WARNING
    qualname = sqlalchemy
    [loggers]
    keys = root,keystone
  policy.yaml: |-
    
  ports.conf: |-
    ""
  sso_callback_template.html: |-
    <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>Keystone WebSSO redirect</title>
      </head>
      <body>
        <form id="sso" name="sso" action="$host" method="post">
          Please wait...
          <br/>
          <input type="hidden" name="token" id="token" value="$token"/>
          <noscript>
            <input type="submit" name="submit_no_javascript" id="submit_no_javascript"
                value="If your JavaScript is disabled, please click to continue"/>
          </noscript>
        </form>
        <script type="text/javascript">
          window.onload = function() {
            document.forms['sso'].submit();
          }
        </script>
      </body>
    </html>
  mpm_event.conf: |-
    <IfModule mpm_event_module>
      ServerLimit         1024
      StartServers        32
      MinSpareThreads     32
      MaxSpareThreads     256
      ThreadsPerChild     25
      MaxRequestsPerChild 128
      ThreadLimit         720
    </IfModule>
  security.conf: |-
    #
    # Disable access to the entire file system except for the directories that
    # are explicitly allowed later.
    #
    # This currently breaks the configurations that come with some web application
    # Debian packages.
    #
    #<Directory />
    #   AllowOverride None
    #   Require all denied
    #</Directory>

    # Changing the following options will not really affect the security of the
    # server, but might make attacks slightly more difficult in some cases.

    #
    # ServerTokens
    # This directive configures what you return as the Server HTTP response
    # Header. The default is 'Full' which sends information about the OS-Type
    # and compiled in modules.
    # Set to one of:  Full | OS | Minimal | Minor | Major | Prod
    # where Full conveys the most information, and Prod the least.
    ServerTokens Prod

    #
    # Optionally add a line containing the server version and virtual host
    # name to server-generated pages (internal error documents, FTP directory
    # listings, mod_status and mod_info output etc., but not CGI generated
    # documents or custom error documents).
    # Set to "EMail" to also include a mailto: link to the ServerAdmin.
    # Set to one of:  On | Off | EMail
    ServerSignature Off

    #
    # Allow TRACE method
    #
    # Set to "extended" to also reflect the request body (only for testing and
    # diagnostic purposes).
    #
    # Set to one of:  On | Off | extended
    TraceEnable Off

    #
    # Forbid access to version control directories
    #
    # If you use version control systems in your document root, you should
    # probably deny access to their directories. For example, for subversion:
    #
    #<DirectoryMatch "/\.svn">
    #   Require all denied
    #</DirectoryMatch>

    #
    # Setting this header will prevent MSIE from interpreting files as something
    # else than declared by the content type in the HTTP headers.
    # Requires mod_headers to be enabled.
    #
    #Header set X-Content-Type-Options: "nosniff"

    #
    # Setting this header will prevent other sites from embedding pages from this
    # site as frames. This defends against clickjacking attacks.
    # Requires mod_headers to be enabled.
    #
    #Header set X-Frame-Options: "sameorigin"
  wsgi-keystone.conf: |-
    Listen 0.0.0.0:5000

    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy

    SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
    CustomLog /dev/stdout combined env=!forwarded
    CustomLog /dev/stdout proxy env=forwarded

    <VirtualHost *:5000>
        WSGIDaemonProcess keystone-public processes=1 threads=1 user=keystone group=keystone display-name=%{GROUP}
        WSGIProcessGroup keystone-public
        WSGIScriptAlias / /var/www/cgi-bin/keystone/keystone-wsgi-public
        WSGIApplicationGroup %{GLOBAL}
        WSGIPassAuthorization On
        <IfVersion >= 2.4>
          ErrorLogFormat "%{cu}t %M"
        </IfVersion>
        ErrorLog /dev/stdout

        SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
        CustomLog /dev/stdout combined env=!forwarded
        CustomLog /dev/stdout proxy env=forwarded
    </VirtualHost>
