apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      initContainers:
        - command:
          - kubernetes-entrypoint
          name: init
          image: {{ template "entrypoint.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INTERFACE_NAME
            value: eth0
          - name: PATH
            value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
          - name: DEPENDENCY_JOBS
            value: {{ include "helm-toolkit.utils.joinListWithComma" .Values.dependencies.keystone_api.jobs }}
      containers:
        - name: keystone-api
          image: {{ template "keystone.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - /bin/sh
            - -c
            - |
              /tmp/keystone.sh
              /tmp/keystone-api.sh start
          env:
            - name: KEYSTONE_DATABASE_HOST
              value: {{ include "keystone.databaseHost" . | quote }}
            - name: KEYSTONE_DATABASE_PORT
              value: {{ include "keystone.databasePort" . | quote }}
            - name: KEYSTONE_DATABASE_NAME
              value: {{ include "keystone.databaseName" . | quote }}
            - name: KEYSTONE_DATABASE_USER
              value: {{ include "keystone.databaseUser" . | quote }}
            - name: KEYSTONE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keystone-database-password
                  name: {{ .Values.mariadb.auth.existingSecret }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keystone-database-password
                  name: {{ .Values.mariadb.auth.existingSecret }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
          volumeMounts:
          - mountPath: /tmp/keystone.sh
            name: keystone-etc
            readOnly: true
            subPath: keystone.sh
          - mountPath: /tmp/keystone-api.sh
            name: keystone-bin
            readOnly: true
            subPath: keystone-api.sh
      serviceAccount: keystone-api
      serviceAccountName: keystone-api
      volumes:
      - emptyDir: {}
        name: pod-tmp
      - configMap:
          defaultMode: 365
          name: keystone-etc
        name: keystone-etc
      - configMap:
          defaultMode: 365
          name: keystone-bin
        name: keystone-bin

