apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-credential-cleanup
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded, hook-failed
spec:
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      containers:
        - name: keystone-credential-cleanup
          image: {{ template "keystone.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - /bin/sh
            - -c
            - |
              /tmp/keystone.sh
              python /tmp/cred-clean.py
          env:
            - name: OPENSTACK_CONFIG_FILE
              value: /etc/keystone/keystone.conf
            - name: OPENSTACK_CONFIG_DB_SECTION
              value: database
            - name: OPENSTACK_CONFIG_DB_KEY
              value: connection
            - name: KEYSTONE_DATABASE_HOST
              value: {{ include "keystone.databaseHost" . | quote }}
            - name: KEYSTONE_DATABASE_PORT
              value: {{ include "keystone.databasePort" . | quote }}
            - name: KEYSTONE_DATABASE_NAME
              value: {{ include "keystone.databaseName" . | quote }}
            - name: KEYSTONE_DATABASE_USER
              value: {{ include "keystone.databaseUser" . | quote }}
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mariadb-root-password
                  name: {{ index .Values "openstack-dep" "gen-password" "secretName" }}
            - name: KEYSTONE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keystone-database-password
                  name: {{ index .Values "openstack-dep" "gen-password" "secretName" }}
          volumeMounts:
          - mountPath: /tmp
            name: pod-tmp
          - mountPath: /etc/keystone
            name: etckeystone
          - mountPath: /tmp/cred-clean.py
            name: keystone-bin
            readOnly: true
            subPath: cred-clean.py
          - mountPath: /tmp/keystone.sh
            name: keystone-etc
            subPath: keystone.sh
      initContainers:
        - name: init
          image: {{ template "entrypoint.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - kubernetes-entrypoint
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: {{ .Release.Namespace }}:{{ include "keystone.mariadb.fullname" . }}
      restartPolicy: OnFailure
      serviceAccount: {{ .Values.serviceAccountName}}
      serviceAccountName: {{ .Values.serviceAccountName}}
      volumes:
      - emptyDir: {}
        name: pod-tmp
      - emptyDir: {}
        name: etckeystone
      - configMap:
          defaultMode: 365
          name: keystone-bin
        name: keystone-bin
      - configMap:
          defaultMode: 365
          name: keystone-etc
        name: keystone-etc
