apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-db-drop
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded, hook-failed
spec:
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      containers:
        - name: keystone-db-drop
          image: {{ template "kolla.toolbox.image" . }}
          imagePullPolicy: {{ .Values.image.kollaToolboxImage.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - /tmp/db-drop.sh
          env:
            - name: KEYSTONE_DATABASE_HOST
              value: {{ include "keystone.databaseHost" . | quote }}
            - name: KEYSTONE_DATABASE_NAME
              value: {{ .Values.endpoints.oslo_db.database }}
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mariadb-root-password
                  name: {{ index .Values "openstack-dep" "gen-password" "secretName" }}
          volumeMounts:
          - mountPath: /tmp
            name: pod-tmp
          - mountPath: /tmp/db-drop.sh
            name: keystone-bin
            readOnly: true
            subPath: db-drop.sh
      initContainers:
        - name: init
          image: {{ template "entrypoint.image" . }}
          imagePullPolicy: {{ .Values.image.entrypointImage.pullPolicy }}
          command:
            - kubernetes-entrypoint
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            {{- if (index .Values "openstack-dep" "enabled")}}
            - name: DEPENDENCY_SERVICE
              value: {{ .Release.Namespace }}:{{ include "keystone.mariadb.fullname" . }}
            {{- end }}
      restartPolicy: OnFailure
      serviceAccount: {{ .Values.serviceAccountName}}
      serviceAccountName: {{ .Values.serviceAccountName}}
      volumes:
      - emptyDir: {}
        name: pod-tmp
      - configMap:
          defaultMode: 493
          name: keystone-bin
        name: keystone-bin

