apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-db-init
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: keystone-db-init
          image: {{ template "kolla.toolbox.image" . }}
          imagePullPolicy: {{ .Values.image.kollaToolboxImage.pullPolicy }}
          {{- if (index .Values "openstack-dep" "enabled") }}
          command:
            - /bin/sh
            - -c
            - /tmp/db-init.sh
          {{- else }}
          command:
            - /bin/sh
            - -c
            - |
              /tmp/db-init.sh
              python3 /tmp/edit-keystone-etc.py
          {{- end }}
          env:
            - name: KEYSTONE_DATABASE_HOST
              value: {{ include "keystone.databaseHost" . | quote }}
            - name: KEYSTONE_DATABASE_PORT
              value: {{ .Values.endpoints.oslo_db.port | quote }}
            - name: KEYSTONE_DATABASE_NAME
              value: {{ .Values.endpoints.oslo_db.database | quote }}
            - name: KEYSTONE_DATABASE_USER
              value: {{ .Values.endpoints.oslo_db.username | quote }}
            - name: KEYSTONE_DATABASE_URL
              value: {{ index .Values "openstack-dep" "openstackEnv" "mariadbUrl" | quote }}
            - name: KUBERNETES_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: CONFIG_MAP_NAME
              value: keystone-etc
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mariadb-root-password
                  name: {{ index .Values "openstack-dep" "gen-password" "secretName" }}
            - name: KEYSTONE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keystone-database-password
                  name: {{ index .Values "openstack-dep" "gen-password" "secretName" }}
          volumeMounts:
          - mountPath: /tmp
            name: pod-tmp
          - mountPath: /tmp/db-init.sh
            name: keystone-bin
            subPath: db-init.sh
          {{- if not (index .Values "openstack-dep" "enabled") }}
          - mountPath: /tmp/edit-keystone-etc.py
            name: keystone-bin
            subPath: edit-keystone-etc.py
          {{- end }}
      initContainers:
        - name: init
          image: {{ template "entrypoint.image" . }}
          imagePullPolicy: {{ .Values.image.entrypointImage.pullPolicy }}
          command:
            - kubernetes-entrypoint
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            {{- if (index .Values "openstack-dep" "enabled")}}
            - name: DEPENDENCY_SERVICE
              value: {{ .Release.Namespace }}:{{ include "keystone.mariadb.fullname" . }}
            {{- end }}
      restartPolicy: OnFailure
      serviceAccount: {{ .Values.serviceAccountName}}
      serviceAccountName: {{ .Values.serviceAccountName}}
      volumes:
      - emptyDir: {}
        name: pod-tmp
      - configMap:
          defaultMode: 493
          name: keystone-bin
        name: keystone-bin
