apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-credential-setup
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: keystone-credential-setup
          image: {{ template "kolla.toolbox.image" . }}
          imagePullPolicy: {{ .Values.image.kollaToolboxImage.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - python3 /tmp/fernet-manage.py credential_setup
          env:
            - name: KEYSTONE_USER
              value: keystone
            - name: KEYSTONE_GROUP
              value: keystone
            - name: KUBERNETES_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: KEYSTONE_KEYS_REPOSITORY
              value: /etc/keystone/credential-keys/
          volumeMounts:
            - mountPath: /tmp
              name: pod-tmp
            - mountPath: /etc/keystone/credential-keys/
              name: credential-keys
            - mountPath: /tmp/fernet-manage.py
              name: keystone-bin
              subPath: fernet-manage.py
      restartPolicy: OnFailure
      serviceAccount: {{ .Values.serviceAccountName}}
      serviceAccountName: {{ .Values.serviceAccountName}}
      volumes:
      - emptyDir: {}
        name: pod-tmp
      - emptyDir: {}
        name: credential-keys
      - configMap:
          defaultMode: 365
          name: keystone-bin
        name: keystone-bin
