apiVersion: v1
kind: Service
metadata:
  name: keystone-api
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  ports:
   {{- $portInt := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
    - name: ks-pub
      port: {{ tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
      {{ if .Values.network.api.node_port.enabled }}
      nodePort: {{ .Values.network.api.node_port.port }}
      {{ end }}
  {{ if or (.Values.network.api.node_port.enabled) (.Values.network.admin.node_port.enabled) }}
  type: NodePort
  {{ if .Values.network.api.external_policy_local }}
  externalTrafficPolicy: Local
  {{ end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  {{ end }}
