apiVersion: v1
kind: Secret
metadata:
  name: openstack-password
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- range $index, $element := .Values.passwordEnvs }}
  {{- range $key, $values := $element}}
  {{- if not (empty $values) }}
  {{ $key }}: {{ $values | b64enc | quote }}
  {{- else }}
  {{ $key }}: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}