apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  {{ $password := .Values.passwordEnvs }}
  {{- range $key, $values := .Values.passwordEnvs }}
  {{- if not (empty $values) }}
    {{ $key }}: {{ $values | b64enc }}
  {{- else }}
  {{- $_ := set $password $key (randAlphaNum 10 | b64enc) -}}
  {{- end }}
  {{- end }}
  {{- range $key, $values := .Values.passwordEnvs }}
  {{ $key }}: {{ $values }}
  {{- end }}
