{{- if .Values.autoGenPasswd }}
apiVersion: v1
kind: Secret
metadata:
  name: openstack-password
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- range $key, $value := .Values.passwordConfig }}
  {{ $key }}: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}