apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mariadb.secretName }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- if not (empty .Values.mariadb.root.password) }}
  mariadb-root-password: {{ .Values.mariadb.root.password | b64enc | quote }}
  {{- else }}
  mariadb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.mariadb.keystone.password) }}
  mariadb-keystone-password: {{ .Values.mariadb.keystone.password | b64enc | quote }}
  {{- else }}
  mariadb-keystone-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.mariadb.glance.password) }}
  mariadb-glance-password: {{ .Values.mariadb.glance.password | b64enc | quote }}
  {{- else }}
  mariadb-glance-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.mariadb.cinder.password) }}
  mariadb-cinder-password: {{ .Values.mariadb.cinder.password | b64enc | quote }}
  {{- else }}
  mariadb-cinder-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.mariadb.nova.password) }}
  mariadb-nova-password: {{ .Values.mariadb.nova.password | b64enc | quote }}
  {{- else }}
  mariadb-nova-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.mariadb.neutron.password) }}
  mariadb-neutron-password: {{ .Values.mariadb.neutron.password | b64enc | quote }}
  {{- else }}
  mariadb-neutron-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.mariadb.placement.password) }}
  mariadb-placement-password: {{ .Values.mariadb.placement.password | b64enc | quote }}
  {{- else }}
  mariadb-placement-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
