apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.user.secretName }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- if not (empty .Values.user.admin.password) }}
  user-admin-password: {{ .Values.user.admin.password | b64enc | quote }}
  {{- else }}
  user-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.user.keystone.password) }}
  user-keystone-password: {{ .Values.user.keystone.password | b64enc | quote }}
  {{- else }}
  user-keystone-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.user.glance.password) }}
  user-glance-password: {{ .Values.user.glance.password | b64enc | quote }}
  {{- else }}
  user-glance-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.user.cinder.password) }}
  user-cinder-password: {{ .Values.user.cinder.password | b64enc | quote }}
  {{- else }}
  user-cinder-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.user.nova.password) }}
  user-nova-password: {{ .Values.user.nova.password | b64enc | quote }}
  {{- else }}
  user-nova-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.user.neutron.password) }}
  user-neutron-password: {{ .Values.user.neutron.password | b64enc | quote }}
  {{- else }}
  user-neutron-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if not (empty .Values.user.placement.password) }}
  user-placement-password: {{ .Values.user.placement.password | b64enc | quote }}
  {{- else }}
  user-placement-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}