apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.connInfoSecret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
data:
  {{ $env := .Values.openstackEnv }}
  {{- $_ := set $env "rabbitmqUrl"  (include "rabbitmq.connInfo" . | b64enc) -}}
  {{- $_ := set $env "mariadbUrl" (include "memcached.connInfo" . | b64enc) -}}
  {{- $_ := set $env "memcacheUrl" (include "mariadb.connInfo" . | b64enc) -}}
  RABBITMQ_URL: {{ .Values.openstackEnv.rabbitmqUrl }}
  MEMCACHE_URL: {{ .Values.openstackEnv.memcacheUrl }}
  MARIADB_URL: {{ .Values.openstackEnv.mariadbUrl }}
