apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.connInfoSecret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  RABBITMQ_URL: {{ include "rabbitmq.connInfo" . | b64enc | quote }}
  MEMCACHE_URL: {{ include "memcached.connInfo" . | b64enc | quote }}
  MARIADB_URL: {{ include "mariadb.connInfo" . | b64enc | quote }}
