apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-etc
  namespace: {{ .Release.Namespace | quote }}
data:
  cinder.conf: |-
    [DEFAULT]
    debug = False
    log_dir = /var/log/kolla/cinder
    use_forwarded_for = true
    use_stderr = False
    osapi_volume_workers = 5
    volume_name_template = volume-%s
    os_region_name = {{ .Values.endpoints.auth.cinder.region_name }}
    enabled_backends = {{ .Values.conf.volume_type }}
    default_volume_type = {{ .Values.conf.volume_type }}
    osapi_volume_listen = 0.0.0.0
    osapi_volume_listen_port = {{ .Values.service.publicService.port }}
    api_paste_config = /etc/cinder/api-paste.ini
    auth_strategy = keystone
    transport_url = {{ index .Values "keystone" "openstack-dep" "openstackEnv" "rabbitmqUrl" }}
    enable_force_upload = True
    verify_glance_signatures = disabled
    random_select_backend = True

    [oslo_messaging_notifications]
    transport_url = {{ index .Values "keystone" "openstack-dep" "openstackEnv" "rabbitmqUrl" }}
    driver = noop

    [oslo_middleware]
    enable_proxy_headers_parsing = True

    [database]
    connection =  mysql+pymysql://{{ .Values.endpoints.oslo_db.username }}:{{ include "cinder.databasePassword" . }}@{{ index .Values "keystone" "openstack-dep" "openstackEnv" "mariadbUrl" }}/{{ .Values.endpoints.oslo_db.database }}
    connection_recycle_time = 10
    max_pool_size = 1
    max_retries = -1

    [keystone_authtoken]
    www_authenticate_uri = {{ .Values.keystone.endpoints.auth.admin.os_internal_url }}
    auth_url = {{ .Values.keystone.endpoints.auth.admin.os_internal_url }}
    auth_type = password
    project_domain_id = default
    user_domain_id = default
    project_name = service
    username = {{ .Values.endpoints.auth.cinder.username }}
    password = {{ include "cinder.keystone.password" . }}
    memcached_servers = {{ index .Values "keystone" "openstack-dep" "openstackEnv" "memcacheUrl" }}

    [oslo_concurrency]
    lock_path = /var/lib/cinder/tmp

    [privsep_entrypoint]
    helper_command = sudo cinder-rootwrap /etc/cinder/rootwrap.conf privsep-helper --config-file /etc/cinder/cinder.conf

    [{{ .Values.conf.volume_type }}]
    volume_group = {{ .Values.conf.vg_name }}
    volume_driver = {{ .Values.conf.volume_driver }}
    volume_backend_name = {{ .Values.conf.volume_type }}
    target_helper = tgtadm
    target_protocol = iscsi
  cinder-wsgi.conf: |-
    Listen 0.0.0.0:8776
    ServerSignature Off
    ServerTokens Prod
    TraceEnable off

    <VirtualHost *:8776>
        WSGIDaemonProcess cinder-api processes=5 threads=1 user=cinder group=cinder display-name=%{GROUP} python-path=/var/lib/kolla/venv/lib/python3.8/site-packages
        WSGIProcessGroup cinder-api
        WSGIScriptAlias / /var/www/cgi-bin/cinder/cinder-wsgi
        WSGIApplicationGroup %{GLOBAL}
        WSGIPassAuthorization On
        <IfVersion >= 2.4>
          ErrorLogFormat "%{cu}t %M"
        </IfVersion>
        ErrorLog /var/log/kolla/cinder/cinder-api.log
        LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b %D \"%{Referer}i\" \"%{User-Agent}i\"" logformat
        CustomLog /var/log/kolla/cinder/cinder-api-access.log logformat
    </VirtualHost>
  cinder-scheduler.json: |-
    {
        "command": "cinder-scheduler --config-file /etc/cinder/cinder.conf",
        "config_files": [
            {
                "source": "/var/lib/kolla/config_files/cinder.conf",
                "dest": "/etc/cinder/cinder.conf",
                "owner": "cinder",
                "perm": "0600"
            }],
        "permissions": [
            {
                "path": "/var/lib/cinder",
                "owner": "cinder:cinder",
                "recurse": true
            },
            {
                "path": "/var/log/kolla/cinder",
                "owner": "cinder:cinder",
                "recurse": true
            }
        ]
    }
  cinder-volume.json: |-
    {
        "command": "cinder-volume --config-file /etc/cinder/cinder.conf",
        "config_files": [
            {
                "source": "/var/lib/kolla/config_files/cinder.conf",
                "dest": "/etc/cinder/cinder.conf",
                "owner": "cinder",
                "perm": "0600"
            }],
        "permissions": [
            {
                "path": "/var/lib/cinder",
                "owner": "cinder:cinder",
                "recurse": true
            },
            {
                "path": "/var/log/kolla/cinder",
                "owner": "cinder:cinder",
                "recurse": true
            }
        ]
    }
  cinder-api.json: |-
    {
        "command": "apache2 -DFOREGROUND",
        "config_files": [
            {
                "source": "/var/lib/kolla/config_files/cinder.conf",
                "dest": "/etc/cinder/cinder.conf",
                "owner": "cinder",
                "perm": "0600"
            },
            {
                "source": "/var/lib/kolla/config_files/cinder-wsgi.conf",
                "dest": "/etc/apache2/conf-enabled/cinder-wsgi.conf",
                "owner": "cinder",
                "perm": "0600"
            }],
        "permissions": [
            {
                "path": "/var/lib/cinder",
                "owner": "cinder:cinder",
                "recurse": true
            },
            {
                "path": "/var/log/kolla/cinder",
                "owner": "cinder:cinder",
                "recurse": true
            }
        ]
    }
  cinder-backup.json: |-
    {
        "command": "cinder-backup --config-file /etc/cinder/cinder.conf",
        "config_files": [
            {
                "source": "/var/lib/kolla/config_files/cinder.conf",
                "dest": "/etc/cinder/cinder.conf",
                "owner": "cinder",
                "perm": "0600"
            }],
        "permissions": [
            {
                "path": "/var/lib/cinder",
                "owner": "cinder:cinder",
                "recurse": true
            },
            {
                "path": "/var/log/kolla/cinder",
                "owner": "cinder:cinder",
                "recurse": true
            }
        ]
    }
  cinder-db-sync.json: |-
    {
        "command": "/tmp/db-sync.sh",
        "config_files": [
            {
                "source": "/var/lib/kolla/config_files/cinder.conf",
                "dest": "/etc/cinder/cinder.conf",
                "owner": "cinder",
                "perm": "0600"
            },
            {
                "source": "/var/lib/kolla/config_files/db-sync.sh",
                "dest": "/tmp/db-sync.sh",
                "owner": "cinder",
                "perm": "0755"
            }],
        "permissions": [
            {
                "path": "/var/lib/cinder",
                "owner": "cinder:cinder",
                "recurse": true
            },
            {
                "path": "/var/log/kolla/cinder",
                "owner": "cinder:cinder",
                "recurse": true
            }
        ]
    }
