{{- $envAll := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-bin
  namespace: {{ .Release.Namespace | quote }}
data:
  db-init.sh: |
{{- include "common.scripts.db_init" . | indent 4 }}
  db-sync.sh: |
{{- include "common.scripts.db_sync" . | indent 4 }}
  ks-register-services.sh: |
{{- include "common.scripts.ks_register_services" . | indent 4  }}
  ks-register-users.sh: |
{{- include "common.scripts.ks_register_users" . | indent 4  }}
  volume-type-create.sh: |
{{ tuple "bin/_volume_type_create.sh.tpl" . | include "common.utils.template" | indent 4 }}
  lvm-create.sh: |
{{ tuple "bin/_lvm_create.sh.tpl" . | include "common.utils.template" | indent 4 }}
  lvm-clean.sh: |
{{ tuple "bin/_lvm_clean.sh.tpl" . | include "common.utils.template" | indent 4 }}
  cinder-cm-render.py: |
{{ tuple "bin/_cinder_cm_render.py.tpl" . | include "common.utils.template" | indent 4 }}
