apiVersion: batch/v1
kind: Job
metadata:
  name: cinder-db-sync
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: cinder-db-sync
          image: {{ template "cinder.volume.image" . }}
          imagePullPolicy: {{ .Values.image.cinderVolumeImage.pullPolicy }}
          securityContext:
            runAsUser: 0
          env:
            - name: CINDER_KEYSTONE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: cinder-keystone-password
                  name: {{ index .Values "keystone" "openstack-dep" "gen-password" "secretName" }}
            - name: CINDER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: cinder-database-password
                  name: {{ index .Values "keystone" "openstack-dep" "gen-password" "secretName" }}
            - name: OS_INTERNAL_URL
              valueFrom:
                secretKeyRef:
                  key: OS_INTERNAL_URL
                  name: {{ .Values.keystone.secrets.identity.admin }}
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
            - name: KOLLA_SERVICE_NAME
              value: "cinder-db-sync"
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            - name: LANG
              value: "en_US.UTF-8"
            - name: KOLLA_BASE_DISTRO
              value: "ubuntu"
            - name: KOLLA_DISTRO_PYTHON_VERSION
              value: "3.8"
            - name: KOLLA_BASE_ARCH
              value: "x86_64"
            - name: SETUPTOOLS_USE_DISTUTILS
              value: "stdlib"
            - name: PS1
              value: "$(tput bold)($(printenv KOLLA_SERVICE_NAME))$(tput sgr0)[$(id -un)@$(hostname -s) $(pwd)]$ "
            - name: DEBIAN_FRONTEND
              value: "noninteractive"
          volumeMounts:
            - mountPath: /tmp
              name: pod-tmp
            - mountPath: /var/lib/kolla/config_files/cinder.conf
              name: cinder-etc
              subPath: cinder.conf
            - mountPath: /var/lib/kolla/config_files/db-sync.sh
              name: cinder-bin
              subPath: db-sync.sh
            - mountPath: /var/lib/kolla/config_files/config.json
              name: cinder-etc
              subPath: cinder-db-sync.json
      initContainers:
        - name: init
          image: {{ template "entrypoint.image" . }}
          imagePullPolicy: {{ .Values.image.entrypointImage.pullPolicy }}
          command:
            - kubernetes-entrypoint
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_JOBS
              value: {{ include "joinListWithComma" .Values.dependencies.db_sync.jobs }}
      restartPolicy: OnFailure
      serviceAccount: {{ .Values.serviceAccountName}}
      serviceAccountName: {{ .Values.serviceAccountName}}
      volumes:
        - emptyDir: {}
          name: pod-tmp
        - name: cinder-bin
          configMap:
            defaultMode: 493
            name: cinder-bin
        - name: cinder-etc
          configMap:
            defaultMode: 292
            name: cinder-etc
