name: Lint and Test Charts

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add kungze https://kungze.github.io/charts

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct-lint.yaml

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add kungze https://kungze.github.io/charts
          helm repo add cinder https://fightdou.github.io/test-charts

      - name: Run chart-testing (install)
        run: ct install --config .github/ct-install.yaml

